DROP TABLE FactOrder
CREATE TABLE FactOrder(
	fact_key int identity(1,1) primary key,
	Order_ID int,
	Order_amount money,
	Payment_key int foreign key references DimPayments(Payment_SK),
	Delivery_key int foreign key references DimDeliveries(Delivery_SK),
	Store_key int foreign key references DimStores(Store_SK),
	Channel_key int foreign key references DimChannel(Channel_SK),
	Order_details_key int foreign key references DimOrderDetails(Order_Detail_SK),
	Order_delivery_fee money,
	Order_delivery_cost money,
	Order_date int foreign key references DimDate(DateKey),
	Order_date_hour int,
	Order_date_minute int,
	Order_deliver_date int foreign key references DimDate(DateKey),
	Order_deliver_hour int,
	Order_deliver_minute int,
	Insert_date	DateTime,
	Modified_date DateTime,
	accm_txn_create_time datetime,
	accm_txn_complete_time datetime,	txn_process_time_hours AS DATEDIFF(hour, accm_txn_create_time, accm_txn_complete_time),
)
